<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">  
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css" type="text/css" />
    <title>CV BLEU</title>
</head>
<body>
    <header class="headerBlue">
            <h1 class="titleHeader"> NOM Prénom</h1>
            <h2 class="subtitleHeader"> Intitulé du poste</h2>
    </header>
    <main>
        <section class="col blocInfo">
            <h2 class="blue h2Title">INFORMATIONS</h3>
            <h3 class="title blue">Contact</h4>
            <div class"email">
                <h4 class="titleMail blue">Email</h5>
                <p>Lesguer.mikael@hotmail.fr</p>
            </div>
            <div class="tel ">
                <h4 class="titleTel blue">Téléphone</h5>
                <p>07.07.07.07.07</p>
            </div>
            <div class="link">
                <h4 class="titleLink blue">Linkedin</h5>
                <p>https/linkedin.mlo.fr</p>
            </div>
            <div class="git">
                <h4 class="titleGit blue">GitHub</h5>
                <p>https://github.com/MikaelLESGUER</p>
            </div>
            <section class="blocBio" >
                <h3 class="blue title">Biographie</h4>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                magna aliquam erat volutpat. Ut wisi enim ad minim veniam,
                quis nostrud exerci tation ullamcorper suscipit lobortis nisl
                ut aliquip ex ea commodo consequat. Duis autem vel eum iriure
                dolor in hendrerit in vulputate velit esse molestie consequat,
                vel illum dolore eu feugiat nulla facilisis at vero eros et
                accumsan et iusto odio dignissim qui blandit praesent luptatum
                zzril delenit augue duis dolore te feugait nulla facilisi.</p>
            </section>
            <section class="loisir">
                <h3 class="blue title">Loisir</h3>
                <ul>
                    <li>Jeux de stratégie</li>
                    <li>Violon</li>
                    <li>Derby</li>
                    <li>Roller</li>
                </ul>
            </section>
        </section>
        <section class="col blocComp">
            <h2 class="blue h2Title title">COMPÉTENCE</h3>
            <div class="langProg">
                <h3 class="blue title">Langages de programmations</h4>
                <ul>
                    <li>HTML</li>
                    <li>CSS</li>
                    <li>Javascript</li>
                    <li>PHP</li>
                    <li>SQL</li>
                </ul>
            </div>
            <div class="fram">
                <h3 class="blue title">Framework & Librairies</h4>
                <ul>
                    <li>SaaS</li>
                    <li>Bootstrap</li>
                    <li>Symfony</li>
                    <li>Laravel</li>
                </ul>
            </div>
            <div class="log">
                <h3 class="blue title">Logiciels</h4>
                <ul>
                    <li>Photoshop</li>
                    <li>Illustrator</li>
                    <li>Xd</li>
                    <li>Figma</li>
                </ul>
            </div>
            <div class="langue">
                <h3 class="blue title">Langues</h4>
                <ul>
                    <li>Francais</li>
                    <li>Anglais</li>
                    <li>Arabe</li>
                </ul>
            </div>
        </section>
    </main>
</body>
</html>